// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTemplate.Models;

#nullable disable

namespace WebTemplate.Migrations
{
    [DbContext(typeof(IspitContext))]
    [Migration("20251029195619_V1")]
    partial class V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebTemplate.Models.Racun", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<long>("CenaKomunalija")
                        .HasColumnType("bigint");

                    b.Property<long>("CenaStruje")
                        .HasColumnType("bigint");

                    b.Property<long>("CenaVode")
                        .HasColumnType("bigint");

                    b.Property<string>("Mesec")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Placen")
                        .HasColumnType("bit");

                    b.Property<int?>("RacunStanID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RacunStanID");

                    b.ToTable("racuni");
                });

            modelBuilder.Entity("WebTemplate.Models.Stan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<long>("BrClanova")
                        .HasColumnType("bigint");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Povrsina")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("stanovi");
                });

            modelBuilder.Entity("WebTemplate.Models.Racun", b =>
                {
                    b.HasOne("WebTemplate.Models.Stan", "RacunStan")
                        .WithMany("StanRacuni")
                        .HasForeignKey("RacunStanID");

                    b.Navigation("RacunStan");
                });

            modelBuilder.Entity("WebTemplate.Models.Stan", b =>
                {
                    b.Navigation("StanRacuni");
                });
#pragma warning restore 612, 618
        }
    }
}
